In [0]:
import torch


In [0]:
w=torch.tensor(3.0,requires_grad=True)
b=torch.tensor(1.0,requires_grad=True)

In [4]:
w,b

(tensor(3., requires_grad=True), tensor(1., requires_grad=True))

In [0]:
def forward(x):
  y=w*x +b
  return y
  

In [6]:
x=torch.tensor([[4],[7]]) # 3*4+1 =13 and 3*7 +1=22
forward(x)

tensor([[13.],
        [22.]], grad_fn=<AddBackward0>)

# Create Linear Class

In [0]:
from torch.nn import Linear

In [13]:
torch.manual_seed(1)

In [14]:
model= Linear(in_features=1,out_features=1) # 1 output for 1 input
print(model.bias,model.weight)

Parameter containing:
tensor([-0.4414], requires_grad=True) Parameter containing:
tensor([[0.5153]], requires_grad=True)


In [15]:
x=torch.tensor([[2.0],[3.3]])
print(model(x))

tensor([[0.5891],
        [1.2590]], grad_fn=<AddmmBackward>)


# Custom Modules

In [30]:
import torch.nn as nn 
torch.manual_seed(1)

In [0]:
class LR(nn.Module): # inherent from nn 
  def __init__(self,input_size,output_size): # same as in line 11
    super().__init__()
    self.linear =nn.Linear(input_size,output_size)
  
  def forward_x(self,x): # this is to make predictions
    pred=self.linear(x)
    return pred



In [32]:
model= LR(1,1) # assign parameters next step is to preduct
print(list(model.parameters()))

[Parameter containing:
tensor([[0.5153]], requires_grad=True), Parameter containing:
tensor([-0.4414], requires_grad=True)]


In [0]:
x=torch.tensor([[1.0],[2.0]])
print(model.forward_x(x))

tensor([[0.0739],
        [0.5891]], grad_fn=<AddmmBackward>)
